[workspace]
members = [
    "examples/rust", # 1.10.0+solana.1.16.15
    "yellowstone-grpc-client", # 1.11.0+solana.1.16.15
    "yellowstone-grpc-geyser", # 1.9.0+solana.1.16.15
    "yellowstone-grpc-kafka", # 1.0.0-rc.1+solana.1.16.15
    "yellowstone-grpc-proto", # 1.10.0+solana.1.16.15
]

[profile.release]
debug = true
lto = true
codegen-units = 1
