[package]
name = "solana-geyser-grpc"
version = "0.2.0"
authors = ["Triton One"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1"
bincode = "1"
clap = { version = "3", features = ["cargo", "derive"] }
futures = "0.3"
hyper = { version = "0.14", features = ["server"] }
lazy_static = "1"
log = "0.4"
prometheus = "0.13"
prost = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
solana-geyser-plugin-interface = "=1.13.3"
solana-logger = "=1.13.3"
solana-sdk = "=1.13.3"
solana-transaction-status = "=1.13.3"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "time"] }
tokio-stream = "0.1"
tonic = { version = "0.8", features = ["gzip"] }

[build-dependencies]
anyhow = "1"
cargo-lock = "8"
git-version = "0.3"
tonic-build = "0.8"
vergen = "=7.2.1"
