[workspace]
resolver = "2"
members = [
    "examples/rust", # 1.11.0+solana.1.17.5
    "yellowstone-grpc-client", # 1.12.0+solana.1.17.5
    "yellowstone-grpc-geyser", # 1.11.0+solana.1.17.5
    "yellowstone-grpc-proto", # 1.11.0+solana.1.17.5
    "yellowstone-grpc-tools", # 1.0.0-rc.6+solana.1.17.5
]

[workspace.package]
authors = ["Triton One"]
edition = "2021"
homepage = "https://triton.one"
repository = "https://github.com/rpcpool/yellowstone-grpc"
license = "Apache-2.0"
keywords = ["solana"]

[workspace.dependencies]
solana-account-decoder = "=1.17.5"
solana-geyser-plugin-interface = "=1.17.5"
solana-logger = "=1.17.5"
solana-sdk = "=1.17.5"
solana-transaction-status = "=1.17.5"

[profile.release]
debug = true
lto = true
codegen-units = 1
