[workspace]
members = [
    "examples/rust", # 1.9.0+solana.1.16.1
    "yellowstone-grpc-client", # 1.9.0+solana.1.16.1
    "yellowstone-grpc-geyser", # 1.7.1+solana.1.16.1
    "yellowstone-grpc-proto", # 1.9.0+solana.1.16.1
]

[profile.release]
debug = true
lto = true
codegen-units = 1
