[package]
name = "yellowstone-grpc-client"
version = "1.12.0+solana.1.17.5"
authors = { workspace = true }
edition = { workspace = true }
description = "Yellowstone gRPC Geyser Simple Client"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
publish = true

[dependencies]
bytes = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
thiserror ={ workspace = true }
tonic = { workspace = true }
tonic-health = { workspace = true }
yellowstone-grpc-proto = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
