[package]
name = "triton-grpc-client-simple"
version = "1.0.0+solana.1.15.2"
authors = ["Triton One"]
edition = "2021"

[[bin]]
name = "client"

[dependencies]
anyhow = "1.0.62"
backoff = { version = "0.4.0", features = ["tokio"] }
clap = { version = "3.2.22", features = ["cargo", "derive"] }
env_logger = "0.10.0"
futures = "0.3.24"
log = { version = "0.4.14", features = ["std"] }
triton-grpc-proto = { path = "../../triton-grpc-proto" }
triton-grpc-client = { path = "../../triton-grpc-client" }
tokio = { version = "1.21.2", features = ["rt-multi-thread", "macros", "time"] }
